export const modes = [
  {
    id: 'hidden',
    eyebrow: '01 / infer',
    name: 'Hidden signal',
    short: 'Find what the clues are asking.',
    icon: '◌',
    accent: 'amber',
  },
  {
    id: 'odd',
    eyebrow: '02 / notice',
    name: 'Odd one out',
    short: 'Find the detail that breaks the rule.',
    icon: '✳',
    accent: 'coral',
  },
  {
    id: 'sequence',
    eyebrow: '03 / arrange',
    name: 'Sequence sense',
    short: 'Put the evidence in its natural order.',
    icon: '↗',
    accent: 'mint',
  },
]

export const puzzles = [
  {
    id: 'hidden-time',
    mode: 'hidden',
    difficulty: 'warm-up',
    title: 'Three clues. One invisible constant.',
    description: 'The answer is hiding in the relationship, not any single tile.',
    accent: 'amber',
    questionPlaceholder: 'What do you think these clues are asking?',
    answerPlaceholder: 'Name the invisible constant…',
    questionKeywords: ['repeat', 'measure', 'constant', 'pass', 'passing', 'hold', 'change', 'point', 'time'],
    answerKeywords: ['time', 'moment', 'hours', 'clock'],
    explanation: 'The moon, the tide, and an hourglass all point toward time: something you can measure, feel passing, and never hold still.',
    intendedQuestion: 'What keeps passing even when nothing appears to move?',
    clues: [
      { label: 'moon phase', meta: 'wax / wane', description: 'A moon moving through a repeating cycle of light and shadow.', glyph: '◐', tone: 'night' },
      { label: 'tide chart', meta: 'rise / fall', description: 'A chart tracking water that returns, rises, and falls.', glyph: '≈', tone: 'water' },
      { label: 'hourglass', meta: 'grain by grain', description: 'A glass timer where every falling grain marks passing duration.', glyph: '⌛', tone: 'sand' },
    ],
  },
  {
    id: 'odd-band',
    mode: 'odd',
    difficulty: 'observation',
    title: 'One of these never made the soundcheck.',
    description: 'Every tile belongs to a quiet pattern. One is faking it.',
    accent: 'coral',
    questionPlaceholder: 'What rule do you think is hiding here?',
    answerPlaceholder: 'Choose the tile that breaks it…',
    questionKeywords: ['instrument', 'music', 'sound', 'band', 'play', 'belong', 'belongs', 'odd'],
    answerKeywords: ['bicycle', 'bike', 'wheel'],
    explanation: 'The violin, piano, trumpet, and drum are instruments. The bicycle is the only object that cannot make music as an instrument.',
    intendedQuestion: 'Which tile does not belong to the band?',
    clues: [
      { label: 'violin', meta: 'strings', description: 'A bowed string instrument with a resonant wooden body.', glyph: '♬', tone: 'wine' },
      { label: 'piano', meta: 'keys', description: 'A keyboard instrument with strings struck by felt hammers.', glyph: '▥', tone: 'cream' },
      { label: 'trumpet', meta: 'brass', description: 'A brass instrument whose sound is shaped by buzzing lips and valves.', glyph: '◁', tone: 'gold' },
      { label: 'drum', meta: 'percussion', description: 'A percussion instrument played by striking a stretched surface.', glyph: '◉', tone: 'rose' },
      { label: 'bicycle', meta: 'two wheels', description: 'A human-powered vehicle with two wheels, not a musical instrument.', glyph: '◎', tone: 'mint', odd: true },
    ],
  },
  {
    id: 'sequence-garden',
    mode: 'sequence',
    difficulty: 'pattern',
    title: 'A garden, told out of order.',
    description: 'Tap the evidence into the order the story wants to happen.',
    accent: 'mint',
    questionPlaceholder: 'What story is this sequence answering?',
    answerPlaceholder: 'What is the final result?',
    questionKeywords: ['grow', 'happen', 'first', 'last', 'become', 'garden', 'plant', 'life'],
    answerKeywords: ['fruit', 'apple', 'harvest'],
    explanation: 'A seed comes first, then a sprout, then a blossom, then fruit. The final state answers the hidden “what does it become?” question.',
    intendedQuestion: 'What does the small beginning become?',
    clues: [
      { label: 'fruit', meta: 'the result', description: 'The harvest at the end of the plant’s visible growth story.', glyph: '●', tone: 'coral', order: 4 },
      { label: 'blossom', meta: 'the turning point', description: 'The flower that appears before the final fruit.', glyph: '✺', tone: 'pink', order: 3 },
      { label: 'seed', meta: 'the beginning', description: 'A small beginning containing the possibility of a whole plant.', glyph: '•', tone: 'soil', order: 1 },
      { label: 'sprout', meta: 'the first reach', description: 'The first green growth breaking through the soil.', glyph: '⌁', tone: 'leaf', order: 2 },
    ],
  },
]

export const initialProgress = {
  version: 2,
  lastMode: 'hidden',
  completed: [],
  score: 0,
  streak: 0,
  lastSolvedDate: null,
  attempts: {},
  hints: {},
  drafts: {},
}
